version: '3.8'

services:
  # Database 
  postgres:
    image: postgres:15-alpine
    container_name: uth_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - ./database/init-script:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - uth-net

  # 1. Identity Service
  identity-service:
    build:
      context: .
      dockerfile: ./Backend/identity-service/Dockerfile
    image: huyit2005/uth-identity-service:latest   
    ports:
      - "3001:3001"
    env_file:
      - ./Backend/identity-service/.env
    environment:
      - DOCKER_ENV=true
      - SUBMISSION_SERVICE_URL=http://submission-service:3003/api
      - REVIEW_SERVICE_URL=http://review-service:3004/api
    depends_on:
      - postgres 
    networks:
      - uth-net

  # 2. Conference Service
  conference-service:
    build:
      context: .
      dockerfile: ./Backend/conference-service/dockerfile
    image: huyit2005/uth-conference-service:latest   
    ports:
      - "3002:3002"
    env_file:
      - ./Backend/conference-service/.env
    environment:
      - DOCKER_ENV=true
      - IDENTITY_SERVICE_URL=http://identity-service:3001/api
      - SUBMISSION_SERVICE_URL=http://submission-service:3003/api
      - REVIEW_SERVICE_URL=http://review-service:3004/api
    depends_on:
      - postgres
      - identity-service
    networks:
      - uth-net

  # 3. Review Service
  review-service:
    build:
      context: .
      dockerfile: ./Backend/review-service/Dockerfile
    image: huyit2005/uth-review-service:latest   
    ports:
      - "3004:3004"
    env_file:
      - ./Backend/review-service/.env
    environment:
      - DOCKER_ENV=true
      - CONFERENCE_SERVICE_URL=http://conference-service:3002/api
      - SUBMISSION_SERVICE_URL=http://submission-service:3003/api
    depends_on:
      - postgres
      - conference-service
      - submission-service
    networks:
      - uth-net

  # 4. Submission Service
  submission-service:
    build:
      context: .
      dockerfile: ./Backend/submission-service/Dockerfile
    image: huyit2005/uth-submission-service:latest   
    ports:
      - "3003:3003"
    env_file:
      - ./Backend/submission-service/.env
    environment:
      - DOCKER_ENV=true
      - CONFERENCE_SERVICE_URL=http://conference-service:3002/api
      - REVIEW_SERVICE_URL=http://review-service:3004/api
      - IDENTITY_SERVICE_URL=http://identity-service:3001/api
    depends_on:
      - postgres
      - conference-service
      - identity-service
    networks:
      - uth-net

  # 5. API Gateway
  api-gateway:
    build:
      context: .
      dockerfile: ./Backend/api-gateway/Dockerfile
    image: huyit2005/uth-api-gateway:latest   
    ports:
      - "3000:3000"
    environment:
      - DOCKER_ENV=true
      - IDENTITY_SERVICE_URL=http://identity-service:3001
      - CONFERENCE_SERVICE_URL=http://conference-service:3002
      - SUBMISSION_SERVICE_URL=http://submission-service:3003
      - REVIEW_SERVICE_URL=http://review-service:3004
      - AI_SERVICE_URL=http://ai-service:3005
    depends_on:
      - identity-service
      - conference-service
      - submission-service
      - review-service
      - ai-service
    networks:
      - uth-net

  # 6. AI Service
  ai-service:
    build:
      context: .
      dockerfile: ./Backend/ai-service/dockerfile
    image: huyit2005/uth-ai-service:latest
    ports:
      - "3005:3005"
    env_file:
      - ./Backend/ai-service/.env
    environment:
      - DOCKER_ENV=true
    depends_on:
      - postgres
    networks:
      - uth-net

networks:
  uth-net:
    driver: bridge

volumes:
  postgres_data: