version: '3.8'

services:
  # Database 
  postgres:
    image: postgres:15-alpine
    container_name: uth_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - ./database/init-script:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - uth-net

  identity-service:
    build:
      context: .
      dockerfile: ./apps/identity-service/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=admin
      - DB_PASSWORD=admin123
      - DB_DATABASE=db_identity
    depends_on:
      - postgres 
    networks:
      - uth-net

  conference-service:
    build:
      context: .
      dockerfile: ./apps/conference-service/dockerfile
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=admin
      - DB_PASSWORD=admin123
      - DB_DATABASE=db_conference
    depends_on:
      - postgres
    networks:
      - uth-net

networks:
  uth-net:
    driver: bridge

volumes:
  postgres_data: